/**
 * @file src/types/core.ts
 * @description Master type definitions for the Mr. CoolCat Backoffice system.
 * Covers core entities including Users, Customers, Products, Orders, Stores, Events, and Audit Logs.
 */

// --- Enums ---

/**
 * Role levels for dashboard access.
 */
export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  STORE_MANAGER = 'STORE_MANAGER',
  MARKETING = 'MARKETING',
  SUPPORT = 'SUPPORT',
  CONTENT = 'CONTENT',
}

/**
 * Status of a user account.
 */
export enum UserStatus {
  ACTIVE = 'ACTIVE',
  BANNED = 'BANNED',
}

/**
 * Customer segmentation classification.
 */
export enum CustomerSegment {
  VIP = 'VIP',
  NEW = 'NEW',
  RISK = 'RISK',
  LOYAL = 'LOYAL',
}

/**
 * Lifecycle status of a product.
 */
export enum ProductStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

/**
 * Inventory management strategy for a product.
 */
export enum InventoryType {
  SINGLE = 'SINGLE',
  MULTI_WAREHOUSE = 'MULTI_WAREHOUSE',
}

/**
 * The current state of an order in the fulfillment pipeline.
 */
export enum OrderStatus {
  // Estados tradicionales del backoffice
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAID = 'PAID',
  PREPARING = 'PREPARING',
  READY_TO_SHIP = 'READY_TO_SHIP',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  RETURNED = 'RETURNED',
  CANCELLED = 'CANCELLED',

  // Estados de Stripe/Supabase (minúsculas)
  PENDING = 'pending',
  PROCESSING = 'processing',
  COMPLETED = 'completed',
  FAILED = 'failed',
  CANCELLED_LOWERCASE = 'cancelled',
}

/**
 * Status of an event.
 */
export enum EventStatus {
  UPCOMING = 'UPCOMING',
  PAST = 'PAST',
}

/**
 * Action performed in an audit log entry.
 */
export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
}

// --- Helper Interfaces ---

/**
 * Physical address structure.
 */
export interface Address {
  street: string;
  city: string;
  state: string;
  zipCode: string;
  country: string;
}

/**
 * Coordinates for geolocation.
 */
export interface Coordinates {
  lat: number;
  lng: number;
}

/**
 * Complex object for store opening hours.
 * Map of day (0-6 or name) to open/close times or closed status.
 */
export interface OpeningHours {
  [key: string]: {
    open: string; // e.g., "09:00"
    close: string; // e.g., "22:00"
    isClosed?: boolean;
  };
}

/**
 * Representation of a single item within an order.
 */
export interface OrderItem {
  productId: string;
  variantId?: string;
  name: string;
  sku: string;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
}

/**
 * Represents the changes made in an audit log.
 */
export interface AuditLogChanges {
  before: Record<string, unknown>;
  after: Record<string, unknown>;
}

// --- Core Entities ---

/**
 * Base user entity for authentication and general profile info.
 */
export interface User {
  /** Unique Identifier (UUID) */
  id: string;
  /** Email address */
  email: string;
  /** Full name of the user */
  fullName: string;
  /** Phone number */
  phone?: string;
  /** Role determining access permissions */
  role: UserRole;
  /** URL to the user's avatar image */
  avatarUrl?: string;
  /** Account status */
  status: UserStatus;
  /** Creation timestamp */
  createdAt: Date;
  /** Timestamp of the last successful login */
  lastLogin?: Date;
  /** Flexible JSON object for user preferences and extra data */
  metadata?: Record<string, unknown>;
}

/**
 * Extended user profile for end-customers of the app/ecommerce.
 */
export interface Customer extends User {
  /** Current loyalty points balance */
  pointsBalance: number;
  /** Total value generated by the customer over time */
  lifetimeValue: number;
  /** Marketing segment classification */
  segment: CustomerSegment;
  /** List of saved shipping/billing addresses */
  addresses: Address[];
  /** First name */
  firstName?: string;
  /** Last name */
  lastName?: string;
  /** City */
  city?: string;
  /** Avatar character name (e.g., 'buck', 'candela') */
  avatar?: string;
  /** Address label */
  addressLabel?: string;
  /** Street name */
  street?: string;
  /** Street number */
  number?: string;
  /** Floor/apartment */
  floor?: string;
  /** Postal code */
  postalCode?: string;
  /** Full address combined */
  fullAddress?: string;
  /** Preferred language (es, en) */
  language?: string;
}

/**
 * Product entity representing an item for sale or catalog.
 */
export interface Product {
  /** Unique Identifier */
  id: string;
  /** Stock Keeping Unit */
  sku: string;
  /** Product Name */
  name: string;
  /** URL-friendly identifier */
  slug: string;
  /** Short plain text description */
  description: string;
  /** HTML formatted detailed description */
  richDescription?: string;
  /** Base price before variants */
  basePrice: number;
  /** Array of image URLs */
  images: string[];
  /** Category identifier or name */
  category: string;
  /** Array of searchable tags */
  tags: string[];
  /** Publishing status */
  status: ProductStatus;
  /** Type of inventory tracking */
  inventoryType: InventoryType;
  /** Featured product configuration (e.g., "Cerveza del Mes") */
  featuredConfig?: {
    /** Whether this product is currently featured */
    isFeatured: boolean;
    /** Start date of the featured promotion (ISO date string) */
    featuredStartDate?: string;
    /** End date of the featured promotion (ISO date string) */
    featuredEndDate?: string;
    /** Type of featured promotion (e.g., "beer_of_month", "featured", "highlighted") */
    featuredType?: string;
  };
}

/**
 * Product variant (e.g., size, pack size) linked to a parent product.
 * Matches the Supabase schema for product_variants table.
 */
export interface ProductVariant {
  /** Unique Identifier */
  id: string;
  /** ID of the parent Product */
  productId: string;
  /** Variant specific SKU */
  sku: string;
  /** Variant name (e.g., 'Pack x6', 'Botella 330ml') */
  name: string;
  /** Price of the variant */
  price: number;
  /** Promotional price (optional) */
  promotionalPrice?: number;
  /** Weight in kilograms */
  weightKg: number;
  /** Dimensions (length, width, height in cm) */
  dimensions?: {
    length: number;
    width: number;
    height: number;
  };
  /** Barcode (optional) */
  barcode?: string;
  /** If this is the default variant */
  isDefault: boolean;
  /** Current stock quantity */
  stockQuantity: number;
}

/**
 * @deprecated Use ProductVariant instead
 * Legacy variant interface for backward compatibility
 */
export interface Variant {
  /** Unique Identifier */
  id: string;
  /** ID of the parent Product */
  productId: string;
  /** Variant name (e.g., 'Pack x6') */
  name: string;
  /** Variant specific SKU */
  sku: string;
  /** Price adjustment relative to or overriding base price */
  priceModifier: number;
  /** Current stock level */
  stock: number;
}

/**
 * E-commerce order.
 */
export interface Order {
  /** Unique Identifier */
  id: string;
  /** Human-readable order number */
  orderNumber: string;
  /** ID of the customer who placed the order */
  customerId: string;
  /** Email of the customer */
  customerEmail?: string;
  /** Total order amount */
  totalAmount: number;
  /** Subtotal before shipping and discounts */
  subtotal?: number;
  /** Shipping cost */
  shippingCost?: number;
  /** Discount amount */
  discount?: number;
  /** Current order status */
  status: OrderStatus;
  /** List of items included in the order */
  items: OrderItem[];
  /** Shipping destination */
  shippingAddress: Address;
  /** Billing address */
  billingAddress: Address;
  /** Stripe Payment Intent ID */
  stripePaymentIntentId?: string;
  /** Stripe payment status */
  stripePaymentStatus?: string;
  /** Shipping method (home, pickup) */
  shippingMethod?: string;
  /** Cart data (JSONB from Supabase) */
  cart?: any;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
  /** When the payment was completed */
  paidAt?: Date;
  /** Creation timestamp */
  createdAt: Date;
  /** Last update timestamp */
  updatedAt: Date;
}

/**
 * Physical retail store location.
 */
export interface Store {
  /** Unique Identifier */
  id: string;
  /** Store Name */
  name: string;
  /** Physical address string */
  address: string;
  /** Geolocation coordinates */
  coordinates: Coordinates;
  /** Contact phone number */
  phone?: string;
  /** Whether the store is currently active/open for business logic */
  isActive: boolean;
  /** Weekly opening hours configuration */
  openingHours: OpeningHours;
}

/**
 * Ticketed event or experience.
 */
/**
 * Event entity representing events (tastings, festivals, etc.).
 * Matches the Supabase schema for events table.
 */
export interface Event {
  /** Unique Identifier */
  id: string;
  /** Event Title */
  title: string;
  /** Description of the event */
  description?: string;
  /** URL of cover image */
  coverImageUrl?: string;
  /** URL of hero image (alternative) */
  heroImage?: string;
  /** Category of the event */
  category?: string;
  /** Tags for the event */
  tags?: string[];
  /** Status of the event */
  status: 'published' | 'draft' | 'cancelled';
  /** Start date and time */
  startDate: string;
  /** End date and time */
  endDate: string;
  /** Name of the location */
  locationName?: string;
  /** Location (alternative) */
  location?: string;
  /** City */
  city?: string;
  /** Full address */
  address?: string;
  /** Latitude for map */
  latitude?: number;
  /** Longitude for map */
  longitude?: number;
  /** Maximum capacity */
  capacity?: number;
  /** Maximum attendees (alternative) */
  maxAttendees?: number;
  /** Registered attendees */
  registeredAttendees?: number;
  /** Sold tickets */
  soldTickets?: number;
  /** Price of the event */
  price?: number;
  /** Currency */
  currency?: string;
  /** Whether the event is free */
  isFree?: boolean;
  /** Whether the event is premium */
  isPremium?: boolean;
  /** Whether the event is recurring */
  isRecurring?: boolean;
  /** Recurring (alternative) */
  recurring?: boolean;
  /** Points reward */
  pointsReward?: number;
  /** Distance in km (calculated) */
  distanceKm?: number;
  /** Age restriction */
  ageRestriction?: string;
  /** Creation timestamp */
  createdAt: string;
}

/**
 * Achievement entity representing gamification badges/logros.
 * Matches the Supabase schema for achievements table.
 */
export interface Achievement {
  /** Unique Identifier */
  id: string;
  /** Name of the achievement */
  name: string;
  /** Title (alternative) */
  title?: string;
  /** Description of the achievement */
  description?: string;
  /** Category */
  category?: string;
  /** Difficulty level */
  difficulty?: 'fácil' | 'medio' | 'difícil';
  /** Reward points */
  rewardPoints?: number;
  /** Points reward (alternative) */
  pointsReward?: number;
  /** Reward description */
  rewardDescription?: string;
  /** Reward (alternative) */
  reward?: string;
  /** Reward icon */
  rewardIcon?: string;
  /** Icon name */
  iconName?: string;
  /** Icon (alternative) */
  icon?: string;
  /** URL of locked icon */
  iconLockedUrl?: string;
  /** Icon locked (alternative) */
  iconLocked?: string;
  /** URL of unlocked icon */
  iconUnlockedUrl?: string;
  /** Icon unlocked (alternative) */
  iconUnlocked?: string;
  /** Accent color */
  accentColor?: string;
  /** Status */
  status?: 'published' | 'draft';
  /** Display order */
  displayOrder?: number;
  /** Progress percentage (default) */
  progressPercentage?: number;
  /** Creation timestamp */
  createdAt: string;
}

/**
 * Reward entity representing redeemable rewards with points.
 * Matches the Supabase schema for rewards table.
 */
export interface Reward {
  /** Unique Identifier */
  id: string;
  /** Title of the reward */
  title: string;
  /** Name (alternative) */
  name?: string;
  /** Description of the reward */
  description?: string;
  /** Icon name */
  iconName?: string;
  /** Icon (alternative) */
  icon?: string;
  /** Points required */
  pointsRequired: number;
  /** Points (alternative) */
  points?: number;
  /** Whether the reward is active */
  isActive: boolean;
  /** Available (alternative) */
  available?: boolean;
  /** Category */
  category?: string;
  /** Creation timestamp */
  createdAt: string;
}

/**
 * Security audit log entry for tracking administrative actions.
 */
export interface AuditLog {
  /** Unique Identifier */
  id: string;
  /** ID of the admin who performed the action */
  adminId: string;
  /** Type of action performed */
  action: AuditAction;
  /** Name of the entity type modified (e.g., 'Product') */
  entity: string;
  /** ID of the specific entity modified */
  entityId: string;
  /** JSON object detailing the changes (before/after) */
  changes: AuditLogChanges;
  /** Time of the action */
  timestamp: Date;
}

/**
 * Represents a character entity.
 * Matches the Supabase schema for characters table.
 */
export interface Character {
  /** Unique Identifier */
  id: string;
  /** Character Name */
  name: string;
  /** URL-friendly identifier */
  slug: string;
  /** Role of the character */
  role: string;
  /** Role subtitle */
  roleSubtitle?: string;
  /** Full biography */
  biography?: string;
  /** Short description */
  description?: string;
  /** Signature quote */
  signatureQuote?: string;
  /** Alternative quote */
  quote?: string;
  /** Avatar image URL */
  avatarUrl?: string;
  /** Cover image URL */
  coverImageUrl?: string;
  /** Video presentation URL */
  videoPresentationUrl?: string;
  /** Accent color (hex) */
  accentColor: string;
  /** Theme configuration */
  themeConfig?: {
    primaryColor?: string;
    secondaryColor?: string;
  };
  /** Personality tags */
  personalityTags?: string[];
  /** Personality traits */
  traits?: string[];
  /** Interests */
  interests?: string[];
  /** Likes */
  likes?: string[];
  /** Signature beer name */
  signatureBeer?: string;
  /** Signature beer style */
  signatureBeerStyle?: string;
  /** Alternative beer name */
  cerveza?: string;
  /** Signature beer ABV */
  signatureAbv?: string;
  /** Alternative ABV */
  abv?: string;
  /** Beer type */
  tipo?: string;
  /** If the character is active */
  isActive: boolean;
  /** Creation timestamp */
  createdAt: string;
  
  // Legacy fields for backward compatibility
  /** @deprecated Use accentColor instead */
  color?: string;
  /** @deprecated Use avatarUrl or coverImageUrl instead */
  fullBodyArtUrl?: string;
}
